sketchParameters:
  rows: 40
  cols: 5
  prime: 1337
  heavyHitterThreshold: 100
  heavyChangerThreshold: 50
  sketchCleanUpInterval: 3

logging:
  level: INFO
  loggers:
    #change this one to see the events when they are POSTed
    com.lpineda.dsketch: INFO
    com.lpineda.dsketch.resources.EventResouce: ERROR
  appenders:
    - type: console
      threshold: ALL
      timeZone: UTC
      target: stdout
    - type: file
      currentLogFilename: /var/log/event-receiver.log
      archivedLogFilenamePattern: /var/log/event-receiver-%d.log.gz
      archivedFileCount: 5
server:
  requestLog:
    appenders: []


#docker run --rm --name redis -p 6379:6379 redis
redis:
  # The redis server's address; required.
  db_address: "redis"
