version: '3'
services:
  sketch-ws:
    build:
      context: ../Dockerfile-sketch-ws
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - redis
      - mosquitto
    links:
      - redis
      - mosquitto
  redis:
    image: redis
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
