version: '3'
services:
  receiver:
    image: lpineda/event_receiver
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - redis
      - mosquitto
    links:
      - redis
      - mosquitto
    volumes:
      - /Users/lpineda/workspace/sketch-ws/config.yml:/data/config.yml
  redis:
    image: redis
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
