version: '3'
services:
  receiver:
    image: event_receiver
    ports:
    - "8080:8080"
    - "8081:8081"
    links:
    - redis
    volumes:
    - /Users/lpineda/workspace/sketch-ws/config.yml:/data/config.yml
  redis:
    image: redis