global:
  scrape_interval: 5s
  external_labels:
    monitor: 'my-monitor'
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: 'cadvisor-exporter'
    scrape_interval: 1s
    static_configs:
      - targets: ['cadvisor-exporter:8080']
  - job_name: 'sketch-ws-exporter'
    scrape_interval: 1s
    static_configs:
      - targets: ['sketch-ws:8080']
  - job_name: 'dropwizard-exporter'
    scrape_interval: 1s
    metrics_path: '/dropwizardMetrics'
    static_configs:
      - targets: ['sketch-ws:8080']


